# Generated by Django 2.2.2 on 2019-06-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190617_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Effects',
            new_name='Effect',
        ),
    ]
