# Generated by Django 2.2.2 on 2019-06-18 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_drug_effects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(through='main_app.User_Drug_Effects', to='main_app.Effect'),
        ),
        migrations.CreateModel(
            name='Trip_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('ediable', 'ediable'), ('smoked', 'smoked'), ('oil/lotion', 'oil/lotion'), ('other', 'other')], max_length=1)),
                ('other_drugs_taken', models.CharField(choices=[('Alcohol', 'Alcohol'), ('Cannabis', 'Cannabis'), ('Mushrooms', 'Mushrooms'), ('Payote', 'Payote')], max_length=4)),
                ('drug_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Drug')),
                ('effects', models.ManyToManyField(to='main_app.User_Drug_Effects')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(max_length=200)),
                ('trip_report_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip_Report')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('At the Park', 'At the Park'), ('At a Concert', 'At a Concert'), ('At home', 'At home'), ('Medicinal', 'Medicinal'), ('At Work', 'At Work'), ('Other', 'Other')], max_length=1)),
                ('trip_report_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip_Report')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
