# Generated by Django 2.2.2 on 2019-06-24 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('req_dose', models.CharField(max_length=150)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='New User', max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, max_length=250)),
                ('social_link', models.URLField(blank=True, verbose_name='website')),
                ('exp', models.IntegerField(default=0)),
                ('ghost_key', models.BooleanField(default=False)),
                ('user_key', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=50)),
                ('text_content', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('edible', 'edible'), ('smoked', 'smoked'), ('oil/lotion', 'oil/lotion'), ('other', 'other')], max_length=250)),
                ('other_drugs_taken', models.CharField(choices=[('Alcohol', 'Alcohol'), ('Cannabis', 'Cannabis'), ('Mushrooms', 'Mushrooms'), ('Peyote', 'Peyote')], max_length=250)),
                ('drug_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug', to='main_app.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='User_Drug_Effects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Effect')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TripReportPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('trip_report_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip_Report')),
            ],
        ),
        migrations.AddField(
            model_name='trip_report',
            name='effects',
            field=models.ManyToManyField(to='main_app.User_Drug_Effects'),
        ),
        migrations.AddField(
            model_name='trip_report',
            name='user_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Report_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(max_length=200)),
                ('trip_report_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip_Report')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('At the Park', 'At the Park'), ('At a Concert', 'At a Concert'), ('At home', 'At home'), ('Medicinal', 'Medicinal'), ('At Work', 'At Work'), ('Other', 'Other')], max_length=1)),
                ('trip_report_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Trip_Report')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='https://www.fillmurray.com/200/300', max_length=200)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Drug')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(through='main_app.User_Drug_Effects', to='main_app.Effect'),
        ),
    ]
