# Generated by Django 2.2.2 on 2019-06-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(through='main_app.user_drug_effects', to='main_app.Effect'),
        ),
    ]
