# Generated by Django 2.2 on 2019-06-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190617_1618'),
        ('main_app', '0005_drug_effects'),
    ]

    operations = [
    ]
