# Generated by Django 2.2.2 on 2019-06-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20190618_1441'),
        ('main_app', '0011_auto_20190618_2241'),
    ]

    operations = [
    ]
