# Generated by Django 2.2.2 on 2019-06-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20190619_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_report',
            name='trip_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(through='main_app.User_Drug_Effects', to='main_app.Effect'),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='effects',
            field=models.ManyToManyField(to='main_app.User_Drug_Effects'),
        ),
        migrations.CreateModel(
            name='TripReportPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('trip_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('trip_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Drug')),
            ],
        ),
    ]
