# Generated by Django 2.2 on 2019-06-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20190619_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_report',
            name='trip_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(through='main_app.User_Drug_Effects', to='main_app.Effect'),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='effects',
            field=models.ManyToManyField(to='main_app.User_Drug_Effects'),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='method',
            field=models.CharField(choices=[('ediable', 'ediable'), ('smoked', 'smoked'), ('oil/lotion', 'oil/lotion'), ('other', 'other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='other_drugs_taken',
            field=models.CharField(choices=[('Alcohol', 'Alcohol'), ('Cannabis', 'Cannabis'), ('Mushrooms', 'Mushrooms'), ('Payote', 'Payote')], max_length=250),
        ),
    ]
