# Generated by Django 2.2.2 on 2019-06-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190620_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripreportphoto',
            name='trip_report',
        ),
        migrations.AlterField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(through='main_app.User_Drug_Effects', to='main_app.Effect'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(default='New User', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='effects',
            field=models.ManyToManyField(to='main_app.User_Drug_Effects'),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='method',
            field=models.CharField(choices=[('edible', 'edible'), ('smoked', 'smoked'), ('oil/lotion', 'oil/lotion'), ('other', 'other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='other_drugs_taken',
            field=models.CharField(choices=[('Alcohol', 'Alcohol'), ('Cannabis', 'Cannabis'), ('Mushrooms', 'Mushrooms'), ('Peyote', 'Peyote')], max_length=250),
        ),
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
        migrations.DeleteModel(
            name='TripReportPhoto',
        ),
    ]
