# Generated by Django 2.2.2 on 2019-06-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190620_1626'),
        ('main_app', '0017_auto_20190620_2116'),
    ]

    operations = [
    ]
