# Generated by Django 2.2.2 on 2019-06-21 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_merge_20190621_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(through='main_app.User_Drug_Effects', to='main_app.Effect'),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='drug_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug', to='main_app.Drug'),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='effects',
            field=models.ManyToManyField(to='main_app.User_Drug_Effects'),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='method',
            field=models.CharField(choices=[('edible', 'edible'), ('smoked', 'smoked'), ('oil/lotion', 'oil/lotion'), ('other', 'other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='other_drugs_taken',
            field=models.CharField(choices=[('Alcohol', 'Alcohol'), ('Cannabis', 'Cannabis'), ('Mushrooms', 'Mushrooms'), ('Peyote', 'Peyote')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='user_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
