# Generated by Django 2.2.2 on 2019-06-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20190622_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='effects',
            field=models.ManyToManyField(through='main_app.User_Drug_Effects', to='main_app.Effect'),
        ),
        migrations.AlterField(
            model_name='trip_report',
            name='effects',
            field=models.ManyToManyField(to='main_app.User_Drug_Effects'),
        ),
    ]
