# Generated by Django 2.2 on 2019-06-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20190622_1251'),
        ('main_app', '0018_merge_20190620_2249'),
    ]

    operations = [
    ]
